export const contentCardData = [
  {
    id: 1,
    title: "Alchemist Fragrance",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 60,
    progress: 65,
    updated_at: new Date("2024-11-02"),
    pinned: false,
  },
  {
    id: 2,
    title: "Mystic Forest",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 120,
    progress: 0,
    updated_at: new Date("2024-10-30"),
    pinned: false,
  },
  {
    id: 3,
    title: "Ocean Waves",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 90,
    progress: 45,
    updated_at: new Date("2024-11-01"),
    pinned: false,
  },
  {
    id: 4,
    title: "City Lights",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 180,
    progress: 0,
    updated_at: new Date("2024-10-29"),
    pinned: false,
  },
  {
    id: 5,
    title: "Starry Night",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 75,
    progress: 55,
    updated_at: new Date("2024-10-28"),
    pinned: false,
  },
  {
    id: 6,
    title: "Desert Mirage",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 150,
    progress: 0,
    updated_at: new Date("2024-10-31"),
    pinned: false,
  },
  {
    id: 7,
    title: "Mountain Peaks",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 60,
    progress: 0,
    updated_at: new Date("2024-10-27"),
    pinned: false,
  },
  {
    id: 8,
    title: "Rainy Days",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: true,
    duration: 120,
    progress: 100,
    updated_at: new Date("2024-10-26"),
    pinned: false,
  },
  {
    id: 9,
    title: "Calm Waters",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 100,
    progress: 0,
    updated_at: new Date("2024-10-25"),
    pinned: false,
  },
  {
    id: 10,
    title: "Urban Jungle",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 110,
    progress: 0,
    updated_at: new Date("2024-10-24"),
    pinned: false,
  },
  {
    id: 11,
    title: "Whimsical Dreams",
    typeDesc: "Text to Video",
    image: "https://placehold.co/600x400/png",
    success: false,
    duration: 80,
    progress: 0,
    updated_at: new Date("2024-10-23 "),
    pinned: false,
  },
];
